// ==UserScript==
// @name         Osler Anki Bridge
// @namespace    https://github.com/osler-anki-bridge/osler-anki-bridge
// @version      0.5.0
// @description  Captura e exporta cards da Osler em sessões nomeadas, com fila redundante, avanço confirmado e um único painel.
// @match        https://oslermedicina.com.br/*
// @match        https://*.oslermedicina.com.br/*
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_download
// @grant        GM_setClipboard
// @grant        unsafeWindow
// @run-at       document-idle
// @updateURL    https://raw.githubusercontent.com/leonardolealluz183-bit/osler-anki-bridge/phase-2-android-bridge/docs/osler-anki-bridge-v050.user.js
// @downloadURL  https://raw.githubusercontent.com/leonardolealluz183-bit/osler-anki-bridge/phase-2-android-bridge/docs/osler-anki-bridge-v050.user.js
// ==/UserScript==
(function bootstrapUnifiedBridge(){'use strict';const VERSION='0.5.0';const QUEUE_KEY='oslerAnkiBridge.queue.v1';const QUEUE_BACKUP_KEY='oslerAnkiBridge.queue.backup.v1';const AUDIT_KEY='oslerAnkiBridge.audit.v1';const AUDIT_BACKUP_KEY='oslerAnkiBridge.audit.backup.v1';const PANEL_STATE_KEY='oslerAnkiBridge.panel.v1';const SESSION_KEY='oslerAnkiBridge.sessions.v3';const SESSION_BACKUP_KEY='oslerAnkiBridge.sessions.backup.v3';const LEGACY_SESSION_KEYS=['oslerAnkiBridge.exportSessions.v2','oslerAnkiBridge.exportSessions.backup.v2','oslerAnkiBridge.exportSessions.v1','oslerAnkiBridge.exportSessions.backup.v1',];const PANEL_ID='osler-anki-bridge-v050';const OLD_SESSION_IDS=['osler-anki-session-controls-v0411','osler-anki-session-controls-v0412',];const FALLBACK_DECK='Osler';const CLOZE_SELECTOR='.cloze-answer,[class*="cloze-answer"],[class*="ClozeAnswer"],[class*="clozeAnswer"]';const CAPTURE_RETRY_MS=60;const CAPTURE_TIMEOUT_MS=2800;const ADVANCE_CONFIRM_MS=1400;const ADVANCE_POLL_MS=50;const MAX_AUDIT_EVENTS=1200;const MAX_SESSIONS=50;const LEGACY_RESUME_WINDOW_MS=24*60*60*1000;const SENSITIVE_QUERY_PARAM=/^(token|access_token|auth|authorization|signature|sig|key|jwt)$/i;const pageWindow=typeof unsafeWindow!=='undefined'?unsafeWindow:(typeof window!=='undefined'?window:globalThis);const documentRef=pageWindow.document||globalThis.document;let queue=[];let audit=[];let sessionState={activeId:null,sessions:[]};let panel=null;let loadedAtStart=0;let runStats={added:0,duplicate:0,failed:0};let globalListenersInstalled=false;let lastKnownPath='';let ratingTransaction=null;let nativeReplayUntil=0;let pendingAdvance=null;let panelState={minimized:true,left:null,top:12};let exportDirty=true;let prepared={sessionId:'',sessionTsv:'',sessionName:'',sessionUrl:'',sessionCount:0,log:'',logName:'',logUrl:'',backup:'',};const now=()=>new Date().toISOString();const sleep=(milliseconds)=>new Promise((resolve)=>pageWindow.setTimeout(resolve,milliseconds));const normalizeWhitespace=(value)=>String(value||'').replace(/\s+/g,' ').trim();const normalizeText=(value)=>normalizeWhitespace(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const escapeHtml=(value)=>String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');function stableHash(input){let hash=2166136261;const text=String(input||'');for(let index=0;index<text.length;index+=1){hash^=text.charCodeAt(index);hash=Math.imul(hash,16777619);}
return(hash>>>0).toString(36);}
function slugify(value,max=80){return normalizeText(value).replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,max)||'sessao';}
function safeDeckName(value){return normalizeWhitespace(value).replace(/::+/g,' — ').replace(/[\t\r\n]+/g,' ').slice(0,100)||FALLBACK_DECK;}
function pageMode(locationRef=pageWindow.location){const pathname=String(locationRef?.pathname||'').replace(/\/+$/,'');if(pathname.endsWith('/test/report'))return'report';if(pathname.endsWith('/test'))return'test';return'idle';}
function parseJson(value,fallback=null){if(value==null)return fallback;if(typeof value!=='string')return value;try{return JSON.parse(value);}catch(_error){return fallback;}}
function parseArray(value){const parsed=parseJson(value,[]);return Array.isArray(parsed)?parsed:[];}
async function gmGet(key,fallback){if(typeof GM_getValue!=='function')return fallback;try{const result=GM_getValue(key,fallback);return result&&typeof result.then==='function'?await result:result;}catch(_error){return fallback;}}
async function gmSet(key,value){if(typeof GM_setValue!=='function')return false;try{const result=GM_setValue(key,value);if(result&&typeof result.then==='function')await result;return true;}catch(_error){return false;}}
function readLocal(key,fallback=null){try{const raw=pageWindow.localStorage?.getItem?.(key);return raw==null?fallback:parseJson(raw,fallback);}catch(_error){return fallback;}}
function writeLocal(key,value){try{pageWindow.localStorage?.setItem?.(key,JSON.stringify(value));return true;}catch(_error){return false;}}
function isVerdictOnly(value){const text=normalizeText(value).replace(/[.!?:;,–—-]+$/g,'').trim();return['sim','nao','verdadeiro','falso','correto','correta','incorreto','incorreta'].includes(text);}
function isCitationText(value){const text=normalizeText(value);return text.includes('uptodate')||text.startsWith('fonte:')||text.startsWith('referencia:')||text.startsWith('referência:')||text.startsWith('bibliografia:')||/\bdoi\b/.test(text)||/\b(et al\.?|vol\.|ed\.|edition)\b/.test(text);}
function scrubSensitiveUrl(value){const original=String(value||'').trim();if(!original||/^\s*(javascript|data):/i.test(original))return'';try{const parsed=new URL(original,pageWindow.location?.origin||'https://oslermedicina.com.br');Array.from(parsed.searchParams.keys()).forEach((key)=>{if(SENSITIVE_QUERY_PARAM.test(key))parsed.searchParams.delete(key);});const relative=!/^[a-z][a-z0-9+.-]*:/i.test(original)&&!original.startsWith('//');return relative?`${parsed.pathname}${parsed.search}${parsed.hash}`:parsed.toString();}catch(_error){return original.replace(/([?&])(token|access_token|auth|authorization|signature|sig|key|jwt)=[^&"'\s>]*/gi,'$1').replace(/[?&]+$/g,'');}}
function unwrap(node){const parent=node?.parentNode;if(!parent)return;while(node.firstChild)parent.insertBefore(node.firstChild,node);node.remove();}
function sanitizeHtml(html,doc=documentRef){const template=doc?.createElement?.('template');if(!template){return String(html||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/\s+on[a-z]+=(("[^"]*")|('[^']*')|[^\s>]+)/gi,'').replace(/<mark\b[^>]*class=("|')[^"']*\bosler-highlight\b[^"']*\1[^>]*>/gi,'').replace(/<\/mark>/gi,'').replace(/\s+data-(start|end)-offset=("[^"]*"|'[^']*'|[^\s>]+)/gi,'').replace(/([?&])(token|access_token|auth|authorization|signature|sig|key|jwt)=[^&"'\s>]*/gi,'$1').trim();}
template.innerHTML=html||'';if(!template.content?.querySelectorAll)return template.innerHTML.trim();template.content.querySelectorAll('script,iframe,object,embed').forEach((node)=>node.remove());template.content.querySelectorAll('mark.osler-highlight').forEach(unwrap);template.content.querySelectorAll('[data-start-offset],[data-end-offset]').forEach((node)=>{node.removeAttribute('data-start-offset');node.removeAttribute('data-end-offset');});template.content.querySelectorAll('*').forEach((node)=>{Array.from(node.attributes||[]).forEach((attr)=>{if(/^(on|srcdoc$)/i.test(attr.name))node.removeAttribute(attr.name);if(/^(href|src|xlink:href|formaction)$/i.test(attr.name)){const safe=scrubSensitiveUrl(attr.value);if(safe)node.setAttribute(attr.name,safe);else node.removeAttribute(attr.name);}});});return template.innerHTML.trim();}
function prepareHtmlForAnki(html,doc=documentRef){const clean=sanitizeHtml(html,doc);const template=doc?.createElement?.('template');if(!template){return clean.replace(/<button\b[^>]*>[\s\S]*?<\/button>/gi,'').replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi,'').replace(/<img\b[^>]*>/gi,'<div><em>[Imagem disponível na Osler]</em></div>');}
template.innerHTML=clean;if(!template.content?.querySelectorAll)return clean;template.content.querySelectorAll('button,svg').forEach((node)=>node.remove());template.content.querySelectorAll('img').forEach((image)=>{const placeholder=doc.createElement('div');const alt=normalizeWhitespace(image.getAttribute?.('alt'));placeholder.innerHTML=`<em>[Imagem disponível na Osler${alt ? `:${escapeHtml(alt)}` : ''}]</em>`;image.replaceWith(placeholder);});return template.innerHTML.trim();}
function hiddenByAncestor(element){return Boolean(element?.closest?.('[hidden],[inert],[aria-hidden="true"]'));}
function visibilityMetrics(element){if(!element||element.hidden||hiddenByAncestor(element)||element.closest?.(`#${PANEL_ID}`)){return{visible:false,ratio:0,centerDistance:Infinity,top:Infinity};}
if(OLD_SESSION_IDS.some((id)=>element.closest?.(`#${id}`))){return{visible:false,ratio:0,centerDistance:Infinity,top:Infinity};}
const style=pageWindow.getComputedStyle?.(element);if(style&&(style.display==='none'||style.visibility==='hidden'||Number(style.opacity)===0)){return{visible:false,ratio:0,centerDistance:Infinity,top:Infinity};}
const rect=element.getBoundingClientRect?.();if(!rect||!Number.isFinite(rect.top)){const visible=typeof element.getClientRects==='function'?element.getClientRects().length>0:element.offsetParent!==null;return{visible,ratio:visible?1:0,centerDistance:0,top:0};}
const viewportWidth=Number(pageWindow.innerWidth)||Number(documentRef?.documentElement?.clientWidth)||1920;const viewportHeight=Number(pageWindow.innerHeight)||Number(documentRef?.documentElement?.clientHeight)||1080;const width=Math.max(0,Number(rect.width)||Number(rect.right)-Number(rect.left));const height=Math.max(0,Number(rect.height)||Number(rect.bottom)-Number(rect.top));const intersectionWidth=Math.max(0,Math.min(rect.right,viewportWidth)-Math.max(rect.left,0));const intersectionHeight=Math.max(0,Math.min(rect.bottom,viewportHeight)-Math.max(rect.top,0));const area=Math.max(1,width*height);const intersection=intersectionWidth*intersectionHeight;return{visible:intersection>0&&width>0&&height>0,ratio:intersection/area,centerDistance:Math.abs(Number(rect.top)+height/2-viewportHeight/2),top:Number(rect.top),};}
const isVisible=(element)=>visibilityMetrics(element).visible;function isBefore(first,second){if(!first||!second||first===second||typeof first.compareDocumentPosition!=='function'||!pageWindow.Node)return false;return Boolean(first.compareDocumentPosition(second)&pageWindow.Node.DOCUMENT_POSITION_FOLLOWING);}
function topicStartsParagraph(text,topic){const normalizedText=normalizeText(text);const normalizedTopic=normalizeText(topic).replace(/[.:;,!?–—-]+$/g,'').trim();return Boolean(normalizedText&&normalizedTopic&&normalizedText.startsWith(normalizedTopic));}
function isEntirelyItalic(element){if(!element)return false;const text=normalizeWhitespace(element.textContent);if(!text)return false;if(['EM','I'].includes(String(element.tagName||'').toUpperCase()))return true;const children=Array.from(element.children||[]);if(children.length===1&&['EM','I'].includes(String(children[0].tagName||'').toUpperCase())){return normalizeWhitespace(children[0].textContent)===text;}
const italicText=Array.from(element.querySelectorAll?.('em,i')||[]).map((node)=>normalizeWhitespace(node.textContent)).filter(Boolean).join(' ');return italicText.length>=Math.max(12,Math.floor(text.length*0.8));}
function isLikelyReference(element){if(!element)return true;const text=normalizeWhitespace(element.textContent);const className=normalizeText(element.className);if(element.dataset?.oslerAnkiReference==='true')return true;if(/(reference|referencia|citation|citacao|bibliograph|source|fonte)/.test(className))return true;if(isCitationText(text))return true;if(isEntirelyItalic(element)&&!element.querySelector?.(CLOZE_SELECTOR)&&!/\?$/.test(text))return true;return false;}
function paragraphRemainder(element){if(!element)return'';const strong=element.querySelector?.('strong,b');if(!strong)return normalizeWhitespace(element.textContent);const clone=element.cloneNode?.(true);clone?.querySelector?.('strong,b')?.remove?.();return normalizeWhitespace(clone?.textContent||String(element.textContent||'').replace(strong.textContent||'',''));}
function questionScore(element){if(String(element?.tagName||'').toLowerCase()!=='p')return-Infinity;if(element.closest?.('div.osler-card-explanation'))return-Infinity;if(isLikelyReference(element))return-Infinity;const metrics=visibilityMetrics(element);if(!metrics.visible)return-Infinity;const text=normalizeWhitespace(element.textContent);if(!text||isVerdictOnly(text))return-Infinity;const strong=element.querySelector?.('strong,b');const topic=normalizeWhitespace(strong?.textContent);const remainder=paragraphRemainder(element);if(!strong||!topic||isVerdictOnly(topic)||remainder.length<3)return-Infinity;if(!topicStartsParagraph(text,topic))return-Infinity;let score=80+metrics.ratio*80-metrics.centerDistance/80-Math.max(0,metrics.top)/500;score+=Math.min(text.length,220)/25;if(element.querySelector?.(CLOZE_SELECTOR))score+=240;if(/\?/.test(text))score+=70;if(/[:.]$/.test(text))score+=12;return score;}
function findQuestionElement(doc=documentRef){let best=null;let bestScore=-Infinity;Array.from(doc?.querySelectorAll?.('p')||[]).forEach((candidate)=>{const score=questionScore(candidate);if(score>bestScore){best=candidate;bestScore=score;}});return best;}
function findExplanationForQuestion(question,doc=documentRef){if(!question)return null;const explanations=Array.from(doc?.querySelectorAll?.('div.osler-card-explanation')||[]).filter((element)=>isVisible(element)&&isBefore(question,element));return explanations.sort((first,second)=>{const firstTop=first.getBoundingClientRect?.().top??Infinity;const secondTop=second.getBoundingClientRect?.().top??Infinity;return firstTop-secondTop;})[0]||null;}
function commonAncestor(first,second){if(!first)return null;if(!second)return first.parentElement;const parents=new Set();let current=first;while(current){parents.add(current);current=current.parentElement;}
current=second;while(current){if(parents.has(current))return current;current=current.parentElement;}
return first.parentElement;}
function contentCandidates(root,question,explanation){if(!root||!question)return[];const candidates=Array.from(root.querySelectorAll?.('p,ul,ol,table,blockquote')||[]).filter((node)=>{if(!isVisible(node)||node===question||question.contains?.(node))return false;if(explanation&&(node===explanation||explanation.contains?.(node)))return false;if(!isBefore(question,node))return false;if(explanation&&!isBefore(node,explanation))return false;const text=normalizeWhitespace(node.textContent);if(!text&&!node.querySelector?.('img'))return false;if(isLikelyReference(node)||isCitationText(text))return false;return!/^(anterior|proximo|próximo|salvar|enterrar|feedback|estatisticas|estatísticas)$/i.test(text);});return candidates.filter((node)=>!candidates.some((other)=>other!==node&&other.contains?.(node)));}
function chooseRoot(question,explanation){if(explanation)return commonAncestor(question,explanation);let current=question?.parentElement;let fallback=current;for(let depth=0;current&&current!==documentRef?.body&&depth<8;depth+=1){fallback=current;if(contentCandidates(current,question,null).length)return current;current=current.parentElement;}
return fallback;}
function replaceClozesWithBlank(root,doc=documentRef){Array.from(root?.querySelectorAll?.(CLOZE_SELECTOR)||[]).forEach((node)=>{node.replaceWith(doc.createTextNode('[...]'));});}
function clozesInCard(root,question,explanation){if(!root)return[];return Array.from(root.querySelectorAll?.(CLOZE_SELECTOR)||[]).filter((node)=>{if(!isVisible(node))return false;if(explanation&&explanation.contains?.(node))return false;return question.contains?.(node)||isBefore(question,node);});}
function extractResponse(question,explanation,root,doc=documentRef){const allClozes=clozesInCard(root,question,explanation);if(allClozes.length){const items=allClozes.map((node)=>({text:normalizeWhitespace(node.textContent),html:sanitizeHtml(node.innerHTML,doc),})).filter((item)=>item.text||item.html);const contextBlocks=contentCandidates(root,question,explanation).filter((block)=>allClozes.some((cloze)=>block.contains?.(cloze)));const contextHtml=[];const contextText=[];contextBlocks.forEach((block)=>{const clone=block.cloneNode(true);replaceClozesWithBlank(clone,doc);contextHtml.push(sanitizeHtml(clone.outerHTML||clone.innerHTML,doc));contextText.push(normalizeWhitespace(clone.textContent));});return{answer:{source:question.querySelector?.(CLOZE_SELECTOR)?'question-cloze':'body-cloze',items,text:items.map((item)=>item.text).filter(Boolean).join('; '),html:items.map((item)=>item.html).filter(Boolean).join('; '),},frontContext:{text:contextText.join(' '),html:contextHtml.join('\n')},};}
const candidates=contentCandidates(root,question,explanation);if(!candidates.length){return{answer:{source:'missing',items:[],text:'',html:''},frontContext:{text:'',html:''}};}
const remaining=[...candidates];const promptBlocks=[];while(remaining.length&&promptBlocks.length<2){const candidate=remaining[0];const tag=String(candidate.tagName||'').toLowerCase();const text=normalizeWhitespace(candidate.textContent);if(tag!=='p'||!/\?$/.test(text)||candidate.querySelector?.(CLOZE_SELECTOR))break;promptBlocks.push(remaining.shift());}
let selected=[];const firstList=remaining.find((node)=>['ul','ol','table'].includes(String(node.tagName||'').toLowerCase()));if(firstList)selected=[firstList];else{for(const node of remaining){if(isLikelyReference(node)||isCitationText(normalizeWhitespace(node.textContent)))break;selected.push(node);if(selected.length>=4)break;}}
const items=[];selected.forEach((block)=>{const listItems=Array.from(block.querySelectorAll?.('li')||[]);(listItems.length?listItems:[block]).forEach((node)=>{items.push({text:normalizeWhitespace(node.textContent),html:sanitizeHtml(node.innerHTML,doc)});});});return{answer:{source:explanation?'intermediate-block':'card-body',items,text:items.map((item)=>item.text).filter(Boolean).join('\n'),html:selected.map((node)=>sanitizeHtml(node.outerHTML||node.innerHTML,doc)).join('\n'),},frontContext:{text:promptBlocks.map((node)=>normalizeWhitespace(node.textContent)).join(' '),html:promptBlocks.map((node)=>sanitizeHtml(node.outerHTML||node.innerHTML,doc)).join('\n'),},};}
function extractCard(doc=documentRef){if(pageMode()!=='test')return null;const questionElement=findQuestionElement(doc);if(!questionElement)return null;const explanationElement=findExplanationForQuestion(questionElement,doc);const root=chooseRoot(questionElement,explanationElement);if(!root)return null;const questionClone=questionElement.cloneNode(true);replaceClozesWithBlank(questionClone,doc);const topicElement=questionElement.querySelector('strong,b');const topic=normalizeWhitespace(topicElement?.textContent).replace(/[\s.:;,!?–—-]+$/u,'');const response=extractResponse(questionElement,explanationElement,root,doc);const explanationText=explanationElement?normalizeWhitespace(explanationElement.textContent):'';const explanationHtml=explanationElement?sanitizeHtml(explanationElement.innerHTML,doc):'';const card={id:'',trigger:'',capturedAt:now(),url:pageWindow.location?.href||'',question:{text:normalizeWhitespace([questionClone.textContent,response.frontContext.text].filter(Boolean).join(' ')),html:[sanitizeHtml(questionClone.innerHTML,doc),response.frontContext.html].filter(Boolean).join('\n'),revealedText:normalizeWhitespace(questionElement.textContent),revealedHtml:sanitizeHtml(questionElement.innerHTML,doc),},answer:response.answer,explanation:{text:explanationText,html:explanationHtml},topic:{text:topic,html:sanitizeHtml(topicElement?.innerHTML||escapeHtml(topic),doc)},deck:{text:topic,html:sanitizeHtml(topicElement?.innerHTML||escapeHtml(topic),doc)},};card.id=stableHash([card.topic.text,card.question.text,card.answer.text,card.explanation.text].join('\n---\n'));return card;}
function validateCard(card){const question=normalizeWhitespace(card?.question?.text);const answer=normalizeWhitespace(card?.answer?.text);const answerHtml=String(card?.answer?.html||'');const answerSource=String(card?.answer?.source||'');const topic=normalizeWhitespace(card?.topic?.text);const reasons=[];if(!question)reasons.push('pergunta vazia');if(!answer&&!/<(img|li|ul|ol|table)\b/i.test(answerHtml))reasons.push('resposta vazia');if(!answerSource.includes('cloze')&&(answer.includes('[...]')||answerHtml.includes('[...]')))reasons.push('resposta ainda não revelada');if(isVerdictOnly(question))reasons.push('pergunta é só um veredito');if(isVerdictOnly(topic))reasons.push('assunto é só um veredito');return{valid:reasons.length===0,reasons};}
function mergeCardArrays(...arrays){const merged=[];const ids=new Set();arrays.flat().forEach((card)=>{const id=String(card?.id||'');if(!id||ids.has(id)||!validateCard(card).valid)return;ids.add(id);merged.push(card);});return merged;}
function auditIdentity(entry){return[entry?.at,entry?.status,entry?.id,entry?.trigger,entry?.detail].map((part)=>String(part||'')).join('|');}
function mergeAuditArrays(...arrays){const merged=[];const keys=new Set();arrays.flat().forEach((entry)=>{if(!entry||typeof entry!=='object')return;const key=auditIdentity(entry);if(keys.has(key))return;keys.add(key);merged.push(entry);});return merged.sort((first,second)=>String(first.at||'').localeCompare(String(second.at||''))).slice(-MAX_AUDIT_EVENTS);}
function normalizeSession(raw){if(!raw||typeof raw!=='object'||!raw.id||!normalizeWhitespace(raw.name))return null;return{id:String(raw.id),name:normalizeWhitespace(raw.name),startedAt:String(raw.startedAt||''),endedAt:raw.endedAt?String(raw.endedAt):null,cardIds:Array.from(new Set(Array.isArray(raw.cardIds)?raw.cardIds.map(String).filter(Boolean):[])),};}
function normalizeSessionState(raw){const parsed=parseJson(raw,null);const sessions=Array.isArray(parsed?.sessions)?parsed.sessions.map(normalizeSession).filter(Boolean).slice(-MAX_SESSIONS):[];const requestedActive=parsed?.activeId?String(parsed.activeId):null;const active=sessions.find((session)=>session.id===requestedActive&&!session.endedAt);return{activeId:active?.id||null,sessions};}
function mergeSessionStates(...rawStates){const byId=new Map();rawStates.map(normalizeSessionState).forEach((candidate)=>{candidate.sessions.forEach((session)=>{const current=byId.get(session.id);if(!current){byId.set(session.id,session);return;}
byId.set(session.id,{...current,...session,cardIds:Array.from(new Set([...(current.cardIds||[]),...(session.cardIds||[])])),endedAt:current.endedAt||session.endedAt||null,});});});const sessions=Array.from(byId.values()).sort((a,b)=>String(a.startedAt).localeCompare(String(b.startedAt))).slice(-MAX_SESSIONS);const requestedActives=rawStates.map(normalizeSessionState).map((state)=>state.activeId).filter(Boolean);const unended=sessions.filter((session)=>!session.endedAt);const active=[...unended].reverse().find((session)=>requestedActives.includes(session.id))||unended.at(-1)||null;return{activeId:active?.id||null,sessions};}
function deriveIdsFromAudit(events,startedAt,endedAt=null){const ids=[];const seen=new Set();events.forEach((entry)=>{const at=String(entry?.at||'');const id=String(entry?.id||'');const status=String(entry?.status||'');if(!at||at<startedAt||(endedAt&&at>endedAt))return;if(!['added','duplicate'].includes(status)||!id||seen.has(id))return;seen.add(id);ids.push(id);});return ids;}
function repairLegacySessions(state,events,referenceTime=Date.now()){const repaired=normalizeSessionState(state);repaired.sessions.forEach((session)=>{const derived=deriveIdsFromAudit(events,session.startedAt,session.endedAt);session.cardIds=Array.from(new Set([...(session.cardIds||[]),...derived]));});const active=repaired.sessions.find((session)=>session.id===repaired.activeId&&!session.endedAt);if(active){const activeStarted=Date.parse(active.startedAt)||referenceTime;const previous=[...repaired.sessions].filter((session)=>session.id!==active.id&&normalizeText(session.name)===normalizeText(active.name)).filter((session)=>{const time=Date.parse(session.endedAt||session.startedAt)||0;return time<=activeStarted&&activeStarted-time<=LEGACY_RESUME_WINDOW_MS;}).sort((a,b)=>String(b.endedAt||b.startedAt).localeCompare(String(a.endedAt||a.startedAt)))[0];if(previous&&previous.cardIds.length>0){active.cardIds=Array.from(new Set([...(previous.cardIds||[]),...(active.cardIds||[])]));active.startedAt=previous.startedAt||active.startedAt;}}
repaired.sessions=repaired.sessions.slice(-MAX_SESSIONS);return repaired;}
function activeSession(){return sessionState.sessions.find((session)=>session.id===sessionState.activeId&&!session.endedAt)||null;}
function latestSession(){return activeSession()||sessionState.sessions.at(-1)||null;}
function cardsForSession(session=latestSession()){if(!session)return[];const byId=new Map(queue.map((card)=>[String(card.id),card]));return(session.cardIds||[]).map((id)=>byId.get(String(id))).filter(Boolean);}
async function loadState(){const[gmQueue,gmQueueBackup,gmAudit,gmAuditBackup,gmPanel,gmSessions,gmSessionsBackup,]=await Promise.all([gmGet(QUEUE_KEY,[]),gmGet(QUEUE_BACKUP_KEY,[]),gmGet(AUDIT_KEY,[]),gmGet(AUDIT_BACKUP_KEY,[]),gmGet(PANEL_STATE_KEY,null),gmGet(SESSION_KEY,null),gmGet(SESSION_BACKUP_KEY,null),]);queue=mergeCardArrays(parseArray(gmQueue),parseArray(gmQueueBackup),parseArray(readLocal(QUEUE_KEY,[])),parseArray(readLocal(QUEUE_BACKUP_KEY,[])),);audit=mergeAuditArrays(parseArray(gmAudit),parseArray(gmAuditBackup),parseArray(readLocal(AUDIT_KEY,[])),parseArray(readLocal(AUDIT_BACKUP_KEY,[])),);const sessionSources=[gmSessions,gmSessionsBackup,readLocal(SESSION_KEY,null),readLocal(SESSION_BACKUP_KEY,null),...LEGACY_SESSION_KEYS.map((key)=>readLocal(key,null)),];sessionState=repairLegacySessions(mergeSessionStates(...sessionSources),audit);const localPanel=readLocal(PANEL_STATE_KEY,null);const recoveredPanel=gmPanel&&typeof gmPanel==='object'?gmPanel:localPanel;if(recoveredPanel&&typeof recoveredPanel==='object'){panelState={minimized:recoveredPanel.minimized!==false,left:Number.isFinite(Number(recoveredPanel.left))?Number(recoveredPanel.left):null,top:Number.isFinite(Number(recoveredPanel.top))?Number(recoveredPanel.top):12,};}
loadedAtStart=queue.length;await Promise.all([persistQueue(),persistAudit(),persistSessions(),persistPanelState()]);}
async function persistQueue(){exportDirty=true;const snapshot=JSON.parse(JSON.stringify(queue));await Promise.all([gmSet(QUEUE_KEY,snapshot),gmSet(QUEUE_BACKUP_KEY,snapshot)]);writeLocal(QUEUE_KEY,snapshot);writeLocal(QUEUE_BACKUP_KEY,snapshot);}
async function persistAudit(){exportDirty=true;audit=audit.slice(-MAX_AUDIT_EVENTS);const snapshot=JSON.parse(JSON.stringify(audit));await Promise.all([gmSet(AUDIT_KEY,snapshot),gmSet(AUDIT_BACKUP_KEY,snapshot)]);writeLocal(AUDIT_KEY,snapshot);writeLocal(AUDIT_BACKUP_KEY,snapshot);}
async function persistSessions(){exportDirty=true;const snapshot=JSON.parse(JSON.stringify(sessionState));await Promise.all([gmSet(SESSION_KEY,snapshot),gmSet(SESSION_BACKUP_KEY,snapshot)]);writeLocal(SESSION_KEY,snapshot);writeLocal(SESSION_BACKUP_KEY,snapshot);}
async function persistPanelState(){const snapshot={minimized:panelState.minimized,left:panelState.left,top:panelState.top,};writeLocal(PANEL_STATE_KEY,snapshot);await gmSet(PANEL_STATE_KEY,snapshot);}
function shortLabel(value,maxLength=115){const text=normalizeWhitespace(value)||'pergunta não identificada';return text.length>maxLength?`${text.slice(0, maxLength - 1)}…`:text;}
function setMessage(message,state=''){const target=panel?.querySelector?.('[data-role="message"]');if(!target)return;target.textContent=message||'';target.dataset.state=state;target.style.color=state==='failed'?'#a40000':state==='added'?'#176317':'#222';}
async function recordAudit(status,trigger,card,detail=''){const session=activeSession();const entry={at:now(),status,trigger,detail,id:card?.id||'',topic:normalizeWhitespace(card?.topic?.text),question:normalizeWhitespace(card?.question?.text),answer:normalizeWhitespace(card?.answer?.text),queueSize:queue.length,sessionId:session?.id||'',sessionName:session?.name||'',url:scrubSensitiveUrl(pageWindow.location?.href||''),};audit.push(entry);if(Object.prototype.hasOwnProperty.call(runStats,status))runStats[status]+=1;await persistAudit();return entry;}
function assignCardToActiveSession(cardId){const session=activeSession();const id=String(cardId||'');if(!session||!id)return false;if(session.cardIds.includes(id))return false;session.cardIds.push(id);return true;}
async function commitCard(card,trigger){const validation=validateCard(card);if(!validation.valid)return{status:'not-ready',card:null,reasons:validation.reasons};const copy=JSON.parse(JSON.stringify(card));copy.trigger=trigger;copy.capturedAt=now();const duplicate=queue.find((item)=>item.id===copy.id);const storedCard=duplicate||copy;const status=duplicate?'duplicate':'added';if(!duplicate){queue.push(copy);await persistQueue();}
const assigned=assignCardToActiveSession(storedCard.id);if(assigned)await persistSessions();await recordAudit(status,trigger,copy,duplicate?`ID já presente na fila${assigned ? '; incluído na sessão ativa' : ''}`:`adicionado à fila${assigned ? ' e à sessão ativa' : ''} antes de avançar`,);const session=activeSession();if(status==='duplicate'){setMessage(session?`DUPLICADO, MAS INCLUÍDO NA SESSÃO “${session.name}” — ${shortLabel(copy.question.text)}`:`DUPLICADO — ${shortLabel(copy.question.text)}`,'duplicate',);}else{setMessage(session?`SALVO NA SESSÃO “${session.name}” — ${shortLabel(copy.question.text)}`:`SALVO NA FILA GERAL — ${shortLabel(copy.question.text)}`,'added',);}
renderPanel();return{status,card:storedCard,reasons:[],assigned};}
async function capture(trigger,doc=documentRef){if(pageMode()!=='test'){setMessage('Captura pausada nesta página. Volte ao card.','failed');return{status:'failed',card:null,reasons:['fora da tela de teste']};}
const card=extractCard(doc);const result=await commitCard(card,trigger);if(result.status!=='not-ready')return result;const detail=result.reasons.join(', ')||'card não identificado';await recordAudit('failed',trigger,card,detail);setMessage(`NÃO SALVO — ${shortLabel(findQuestionElement(doc)?.textContent)} — ${detail}`,'failed');renderPanel();return{status:'failed',card:null,reasons:result.reasons};}
function triggerForButton(element){const text=normalizeText([element?.textContent,element?.innerText,element?.getAttribute?.('aria-label'),element?.getAttribute?.('title'),].filter(Boolean).join(' '));if(text.includes('acertei')||text.includes('normal')||text.includes('facil'))return null;if(text.includes('errei')||text.includes('errou'))return'Errei';if(text.includes('dificil'))return'Difícil';return null;}
function triggerFromStructure(target){const button=target?.closest?.('button,[role="button"]');const group=button?.closest?.('[class*="ButtonsContainer"],[class*="MetacognitionContainer"]');if(!button||!group?.querySelectorAll)return null;const buttons=Array.from(group.querySelectorAll('button,[role="button"]')).filter((candidate)=>{return String(candidate.className||'').includes('SRSButton')||Boolean(candidate.closest?.('[class*="MetacognitionContainer"]'));});const index=buttons.indexOf(button);if(index===0)return'Errei';if(index===1)return'Difícil';return null;}
function ratingTrigger(target){let current=target?.closest?.('button,[role="button"]')||target;for(let depth=0;current&&depth<8;depth+=1){if(current.closest?.(`#${PANEL_ID}`))return null;const trigger=triggerForButton(current)||triggerFromStructure(current);if(trigger)return trigger;current=current.parentElement;}
return null;}
function findRatingButton(trigger,doc=documentRef){return Array.from(doc?.querySelectorAll?.('button,[role="button"]')||[]).filter((button)=>isVisible(button)&&ratingTrigger(button)===trigger).sort((first,second)=>{const firstMetrics=visibilityMetrics(first);const secondMetrics=visibilityMetrics(second);return(secondMetrics.ratio-firstMetrics.ratio)||(firstMetrics.centerDistance-secondMetrics.centerDistance);})[0]||null;}
function advanceSnapshot(doc=documentRef){const questionElement=findQuestionElement(doc);return{questionElement,questionText:normalizeWhitespace(questionElement?.textContent),hadRatingButtons:Boolean(findRatingButton('Errei',doc)||findRatingButton('Difícil',doc)),};}
function hasAdvanced(snapshot,doc=documentRef){if(!snapshot)return false;if(pageMode()!=='test')return true;const currentQuestion=findQuestionElement(doc);const currentText=normalizeWhitespace(currentQuestion?.textContent);if(snapshot.questionElement&&currentQuestion&&currentQuestion!==snapshot.questionElement)return true;if(snapshot.questionText&&currentText&&currentText!==snapshot.questionText)return true;const hasButtons=Boolean(findRatingButton('Errei',doc)||findRatingButton('Difícil',doc));return Boolean(snapshot.hadRatingButtons&&!hasButtons&&currentQuestion);}
async function waitForAdvance(snapshot,doc=documentRef,timeoutMs=ADVANCE_CONFIRM_MS){const startedAt=Date.now();while(Date.now()-startedAt<timeoutMs){if(hasAdvanced(snapshot,doc))return true;await sleep(ADVANCE_POLL_MS);}
return hasAdvanced(snapshot,doc);}
function nativeButtonClick(trigger,doc,preferredButton=null){const button=preferredButton&&preferredButton.isConnected&&isVisible(preferredButton)?preferredButton:findRatingButton(trigger,doc);if(!button)return false;nativeReplayUntil=Date.now()+2200;button.focus?.({preventScroll:true});button.click();return true;}
function nativePointerSequence(trigger,doc){const button=findRatingButton(trigger,doc);if(!button)return false;nativeReplayUntil=Date.now()+2200;const rect=button.getBoundingClientRect?.()||{left:0,top:0,width:1,height:1};const init={bubbles:true,cancelable:true,composed:true,view:pageWindow,clientX:Number(rect.left||0)+Number(rect.width||1)/2,clientY:Number(rect.top||0)+Number(rect.height||1)/2,button:0,buttons:1,};const PointerCtor=pageWindow.PointerEvent||pageWindow.MouseEvent;const MouseCtor=pageWindow.MouseEvent;if(PointerCtor){button.dispatchEvent(new PointerCtor('pointerdown',init));button.dispatchEvent(new PointerCtor('pointerup',{...init,buttons:0}));}
if(MouseCtor){button.dispatchEvent(new MouseCtor('mousedown',init));button.dispatchEvent(new MouseCtor('mouseup',{...init,buttons:0}));button.dispatchEvent(new MouseCtor('click',{...init,buttons:0}));}else{button.click();}
return true;}
function nativeKeyboardReplay(trigger,doc=documentRef){const KeyboardCtor=pageWindow.KeyboardEvent;if(!KeyboardCtor)return false;nativeReplayUntil=Date.now()+2200;const descriptor=trigger==='Errei'?{key:'1',code:'Digit1',keyCode:49}:{key:'2',code:'Digit2',keyCode:50};const target=doc.activeElement||doc.body||doc;['keydown','keyup'].forEach((type)=>{const event=new KeyboardCtor(type,{key:descriptor.key,code:descriptor.code,bubbles:true,cancelable:true,composed:true,});try{Object.defineProperty(event,'keyCode',{get:()=>descriptor.keyCode});Object.defineProperty(event,'which',{get:()=>descriptor.keyCode});}catch(_error){}
target.dispatchEvent(event);});return true;}
async function advanceAndConfirm(trigger,doc=documentRef,preferredButton=null,snapshot=null){const baseline=snapshot||advanceSnapshot(doc);if(hasAdvanced(baseline,doc))return{advanced:true,method:'already-advanced'};const attempts=[['click',()=>nativeButtonClick(trigger,doc,preferredButton)],['pointer',()=>nativePointerSequence(trigger,doc)],['keyboard',()=>nativeKeyboardReplay(trigger,doc)],];for(const[method,invoke]of attempts){if(hasAdvanced(baseline,doc))return{advanced:true,method:'already-advanced'};if(!invoke())continue;if(await waitForAdvance(baseline,doc))return{advanced:true,method};}
return{advanced:false,method:''};}
async function waitForValidCard(doc,startedAt){let card=null;let validation={valid:false,reasons:['card não identificado']};while(Date.now()-startedAt<CAPTURE_TIMEOUT_MS){card=extractCard(doc);validation=validateCard(card);if(validation.valid)return{card,validation};await sleep(CAPTURE_RETRY_MS);}
return{card,validation};}
function startRatingTransaction(trigger,doc=documentRef,source='keyboard',preferredButton=null){if(pageMode()!=='test'){return Promise.resolve({status:'failed',reasons:['fora da tela de teste']});}
if(!activeSession()){setMessage('NÃO AVANÇOU — inicie ou retome uma sessão antes de marcar Errei/Difícil.','failed');renderPanel();return Promise.resolve({status:'failed',reasons:['nenhuma sessão ativa'],advanced:false});}
if(ratingTransaction){setMessage('AGUARDE — o card anterior ainda está sendo salvo ou avançado.','waiting');return ratingTransaction.promise;}
const transactionState={trigger,source,phase:'starting',promise:null};ratingTransaction=transactionState;const transaction=(async()=>{const startedAt=Date.now();const questionAtStart=shortLabel(findQuestionElement(doc)?.textContent);const snapshot=advanceSnapshot(doc);transactionState.phase='capturing';renderPanel();setMessage(`AGUARDANDO A RESPOSTA — ${questionAtStart}`,'waiting');const{card,validation}=await waitForValidCard(doc,startedAt);if(!validation.valid){const detail=validation.reasons.join(', ')||'resposta não apareceu';await recordAudit('failed',`${source === 'keyboard' ? 'tecla' : 'botão'} ${trigger}`,card,`bloqueado sem avançar: ${detail}`,);setMessage(`NÃO AVANÇOU — ${questionAtStart} — ${detail}. Revele a resposta e tente uma vez novamente.`,'failed');renderPanel();return{status:'failed',card:null,reasons:validation.reasons,advanced:false};}
const auditTrigger=`${source === 'keyboard' ? 'tecla' : 'botão'} ${trigger}`;let result;if(pendingAdvance&&pendingAdvance.id===card.id){assignCardToActiveSession(card.id);await persistSessions();result={status:'already-saved',card,reasons:[]};setMessage(`JÁ SALVO — tentando apenas avançar: ${shortLabel(card.question.text)}`,'waiting');}else{result=await commitCard(card,auditTrigger);}
if(!['added','duplicate','already-saved'].includes(result.status))return result;transactionState.phase='advancing';renderPanel();setMessage(`SALVO — avançando: ${shortLabel(card.question.text)}`,'waiting');const{advanced,method}=await advanceAndConfirm(trigger,doc,preferredButton,snapshot);if(advanced){pendingAdvance=null;const session=activeSession();setMessage(session?`SALVO E AVANÇOU — sessão “${session.name}” com ${session.cardIds.length} card(s).`:`SALVO E AVANÇOU — ${shortLabel(card.question.text)}`,'added',);}else{pendingAdvance={id:card.id,trigger,at:Date.now()};setMessage(`SALVO, MAS NÃO AVANÇOU — pressione ${trigger === 'Errei' ? '1' : '2'} novamente. Não será duplicado.`,'failed',);}
renderPanel();return{...result,advanced,advanceMethod:method};})();transactionState.promise=transaction;transaction.finally(()=>{ratingTransaction=null;renderPanel();});return transaction;}
function isEditableTarget(target){if(!target)return false;const tag=String(target.tagName||'').toLowerCase();return tag==='input'||tag==='textarea'||tag==='select'||Boolean(target.isContentEditable)||Boolean(target.closest?.('[contenteditable="true"]'));}
function keyTriggerForEvent(event){if(!event||event.repeat||event.ctrlKey||event.altKey||event.metaKey||event.shiftKey)return null;if(isEditableTarget(event.target))return null;if(event.key==='1'||event.code==='Numpad1'||event.code==='Digit1')return'Errei';if(event.key==='2'||event.code==='Numpad2'||event.code==='Digit2')return'Difícil';return null;}
function blockEvent(event){event.preventDefault?.();event.stopPropagation?.();event.stopImmediatePropagation?.();}
function ensureGlobalListeners(doc=documentRef){if(globalListenersInstalled)return;globalListenersInstalled=true;const keyboardHandler=(event)=>{if(pageMode()!=='test'||Date.now()<nativeReplayUntil)return;const trigger=keyTriggerForEvent(event);if(!trigger)return;blockEvent(event);if(event.type==='keydown')startRatingTransaction(trigger,doc,'keyboard');};pageWindow.addEventListener?.('keydown',keyboardHandler,true);pageWindow.addEventListener?.('keyup',keyboardHandler,true);doc.addEventListener('click',(event)=>{if(pageMode()!=='test'||Date.now()<nativeReplayUntil)return;const path=event.composedPath?.()||[event.target];const button=path.find((node)=>ratingTrigger(node));const trigger=ratingTrigger(button);if(!trigger)return;blockEvent(event);startRatingTransaction(trigger,doc,'button',button?.closest?.('button,[role="button"]')||button);},true);}
async function startSession(name){const cleanName=normalizeWhitespace(name);if(!cleanName)throw new Error('Digite o nome da sessão.');if(activeSession())throw new Error('Encerre a sessão atual antes de iniciar outra.');const startedAt=now();const session={id:`${Date.now().toString(36)}-${stableHash(`${cleanName}|${startedAt}`)}`,name:cleanName,startedAt,endedAt:null,cardIds:[],};sessionState.sessions.push(session);sessionState.sessions=sessionState.sessions.slice(-MAX_SESSIONS);sessionState.activeId=session.id;resetPrepared();await persistSessions();renderPanel();setMessage(`Sessão “${cleanName}” iniciada com 0 cards.`,'added');return session;}
async function endSession(){const session=activeSession();if(!session)throw new Error('Não há sessão ativa.');session.endedAt=now();sessionState.activeId=null;await persistSessions();renderPanel();setMessage(`Sessão “${session.name}” encerrada com ${session.cardIds.length} card(s).`,'added');return session;}
function tsvField(value){const normalized=String(value||'').replace(/\r?\n/g,'<br>').replace(/\t/g,' ');return`"${normalized.replace(/"/g, '""')}"`;}
function buildSessionTsv(cards,session,doc=documentRef){const deck=safeDeckName(session?.name);const sessionTag=`sessao_${slugify(session?.name)}`;const headers=['#separator:Tab','#html:true','#tags:osler','#columns:Frente\tVerso\tTags\tBaralho','#tags column:3','#deck column:4',];const rows=cards.filter((card)=>validateCard(card).valid).map((card)=>{const question=prepareHtmlForAnki(card.question.html||escapeHtml(card.question.text),doc);const answer=prepareHtmlForAnki(card.answer.html||escapeHtml(card.answer.text),doc);const explanation=prepareHtmlForAnki(card.explanation?.html||escapeHtml(card.explanation?.text),doc);const topic=normalizeWhitespace(card.topic?.text||FALLBACK_DECK);const front=`<span style="display:none">osler:${escapeHtml(card.id)}</span>${question}`;const explanationBlock=explanation?`<hr><div><strong>Explicação</strong><br>${explanation}</div>`:'';const back=`<div><strong>Resposta</strong><br>${answer}</div>${explanationBlock}<hr><small>Assunto original: ${escapeHtml(topic)} · Sessão: ${escapeHtml(deck)} · ID: ${escapeHtml(card.id)}</small>`;const tags=`osler ${sessionTag} assunto_${slugify(topic)}`;return[front,back,tags,deck].map(tsvField).join('\t');});return`\uFEFF${[...headers, ...rows].join('\n')}\n`;}
function buildLogPayload(){return`${JSON.stringify({
      version: VERSION,
      exportedAt: now(),
      loadedAtStart,
      queueSize: queue.length,
      activeSession: activeSession(),
      sessions: sessionState.sessions,
      runStats,
      pendingAdvance,
      events: audit,
    }, null, 2)}\n`;}
function buildBackupPayload(){return JSON.stringify({format:'osler-anki-bridge-unified-backup',version:VERSION,exportedAt:now(),queue,audit,sessionState,},null,2);}
function revokeUrl(key){const value=prepared[key];if(!value)return;try{pageWindow.URL.revokeObjectURL(value);}catch(_error){}
prepared[key]='';}
function resetPrepared(){revokeUrl('sessionUrl');revokeUrl('logUrl');prepared={sessionId:'',sessionTsv:'',sessionName:'',sessionUrl:'',sessionCount:0,log:'',logName:'',logUrl:'',backup:'',};exportDirty=true;}
function makeObjectUrl(contents,mimeType){return pageWindow.URL.createObjectURL(new pageWindow.Blob([contents],{type:mimeType}));}
function prepareExports(){if(!panel)return null;const session=latestSession();const cards=cardsForSession(session);if(!session)throw new Error('Inicie uma sessão antes de exportar.');if(!cards.length)throw new Error('Essa sessão ainda não possui cards.');const timestamp=Date.now();revokeUrl('sessionUrl');revokeUrl('logUrl');prepared.sessionId=session.id;prepared.sessionTsv=buildSessionTsv(cards,session,documentRef);prepared.sessionName=`osler-anki-${slugify(session.name, 60).replace(/_/g, '-')}-${timestamp}.tsv`;prepared.sessionUrl=makeObjectUrl(prepared.sessionTsv,'text/tab-separated-values;charset=utf-8');prepared.sessionCount=cards.length;prepared.log=buildLogPayload();prepared.logName=`osler-anki-diagnostico-${timestamp}.json`;prepared.logUrl=makeObjectUrl(prepared.log,'application/json;charset=utf-8');prepared.backup=buildBackupPayload();exportDirty=false;const sessionLink=panel.querySelector('[data-role="session-download"]');const logLink=panel.querySelector('[data-role="log-download"]');if(sessionLink){sessionLink.href=prepared.sessionUrl;sessionLink.download=prepared.sessionName;sessionLink.hidden=false;sessionLink.textContent=`Baixar TSV da sessão (${cards.length})`;}
if(logLink){logLink.href=prepared.logUrl;logLink.download=prepared.logName;logLink.hidden=false;}
const tsvArea=panel.querySelector('[data-role="session-tsv-text"]');const logArea=panel.querySelector('[data-role="log-text"]');const backupArea=panel.querySelector('[data-role="backup-text"]');if(tsvArea)tsvArea.value=prepared.sessionTsv;if(logArea)logArea.value=prepared.log;if(backupArea)backupArea.value=prepared.backup;renderPanel();setMessage(`TSV pronto: ${cards.length} cards no baralho “${session.name}”.`,'added');return prepared;}
async function copyText(contents,label){let copied=false;if(typeof GM_setClipboard==='function'){try{const result=GM_setClipboard(contents,'text');if(result&&typeof result.then==='function')await result;copied=true;}catch(_error){copied=false;}}
if(!copied&&pageWindow.navigator?.clipboard?.writeText){try{await pageWindow.navigator.clipboard.writeText(contents);copied=true;}catch(_error){copied=false;}}
setMessage(copied?`${label} copiado.`:'Não foi possível copiar automaticamente. Use o conteúdo bruto.',copied?'added':'failed',);return copied;}
async function downloadWithGm(kind){if(exportDirty||!prepared.sessionTsv)prepareExports();const isSession=kind==='session';const url=isSession?prepared.sessionUrl:prepared.logUrl;const name=isSession?prepared.sessionName:prepared.logName;if(typeof GM_download!=='function')throw new Error('Download do Violentmonkey indisponível. Use o link nativo.');const result=GM_download({url,name,saveAs:false});if(result&&typeof result.then==='function')await result;setMessage(`Download solicitado: ${name}`,'added');return true;}
async function importBackup(text){const parsed=parseJson(String(text||'').trim(),null);if(!parsed)throw new Error('Backup inválido.');const before=queue.length;queue=mergeCardArrays(queue,parseArray(Array.isArray(parsed)?parsed:parsed.queue));audit=mergeAuditArrays(audit,parseArray(parsed.audit));sessionState=repairLegacySessions(mergeSessionStates(sessionState,parsed.sessionState,parsed.sessions?{activeId:parsed.activeId,sessions:parsed.sessions}:null),audit,);await Promise.all([persistQueue(),persistAudit(),persistSessions()]);resetPrepared();renderPanel();setMessage(`Backup importado: ${queue.length - before} card(s) novo(s); ${queue.length} no total.`,'added');return{added:queue.length-before,total:queue.length};}
function clampPanelPosition(left,top){if(!panel)return{left:12,top:12};const rect=panel.getBoundingClientRect();const viewportWidth=Number(pageWindow.innerWidth)||1280;const viewportHeight=Number(pageWindow.innerHeight)||720;return{left:Math.max(4,Math.min(Number(left)||4,Math.max(4,viewportWidth-Math.min(rect.width||420,viewportWidth-8)-4))),top:Math.max(4,Math.min(Number(top)||4,Math.max(4,viewportHeight-Math.min(rect.height||44,viewportHeight-8)-4))),};}
function applyPanelState(){if(!panel)return;const body=panel.querySelector('[data-role="panel-body"]');const toggle=panel.querySelector('[data-action="toggle-panel"]');const title=panel.querySelector('[data-role="panel-title"]');const session=activeSession();if(body)body.hidden=Boolean(panelState.minimized);if(toggle){toggle.textContent=panelState.minimized?'+':'−';toggle.title=panelState.minimized?'Abrir painel':'Minimizar painel';}
if(title){title.textContent=panelState.minimized?session?`Osler Anki ${VERSION} · ${session.name}: ${session.cardIds.length}`:`Osler Anki ${VERSION} · sem sessão`:`Osler Anki Bridge — ${VERSION}`;}
panel.style.maxHeight=panelState.minimized?'48px':'82vh';panel.style.overflow=panelState.minimized?'hidden':'auto';const defaultLeft=Math.max(4,(Number(pageWindow.innerWidth)||1280)
-Math.min(460,(Number(pageWindow.innerWidth)||1280)-16)
-12,);const clamped=clampPanelPosition(panelState.left??defaultLeft,panelState.top??12);panelState.left=clamped.left;panelState.top=clamped.top;panel.style.left=`${clamped.left}px`;panel.style.top=`${clamped.top}px`;panel.style.right='auto';}
function installPanelDragging(){const handle=panel?.querySelector?.('[data-role="drag-handle"]');if(!handle)return;let drag=null;handle.addEventListener('pointerdown',(event)=>{if(event.target?.closest?.('button'))return;const rect=panel.getBoundingClientRect();drag={pointerId:event.pointerId,offsetX:event.clientX-rect.left,offsetY:event.clientY-rect.top,};handle.setPointerCapture?.(event.pointerId);event.preventDefault();});handle.addEventListener('pointermove',(event)=>{if(!drag||event.pointerId!==drag.pointerId)return;const next=clampPanelPosition(event.clientX-drag.offsetX,event.clientY-drag.offsetY);panelState.left=next.left;panelState.top=next.top;panel.style.left=`${next.left}px`;panel.style.top=`${next.top}px`;event.preventDefault();});const finish=(event)=>{if(!drag||(event.pointerId!=null&&event.pointerId!==drag.pointerId))return;handle.releasePointerCapture?.(drag.pointerId);drag=null;persistPanelState();};handle.addEventListener('pointerup',finish);handle.addEventListener('pointercancel',finish);pageWindow.addEventListener?.('resize',()=>{applyPanelState();persistPanelState();});}
function renderPanel(){if(!panel)return;const mode=pageMode();const active=activeSession();const latest=latestSession();const latestCards=cardsForSession(latest);const set=(role,text)=>{const target=panel.querySelector(`[data-role="${role}"]`);if(target)target.textContent=text;};set('session-status',active?`Sessão ativa: ${active.name} · ${active.cardIds.length} card(s)`:latest?`Última sessão: ${latest.name} · ${latest.cardIds.length} card(s) · encerrada`:'Nenhuma sessão criada.');set('queue-status',`${queue.length} card(s) na fila geral · ${loadedAtStart} carregados ao abrir.`);set('run-status',`${runStats.added} novos · ${runStats.duplicate} duplicados · ${runStats.failed} falhas desde que abriu.`);set('mode-status',mode==='test'?ratingTransaction?ratingTransaction.phase==='advancing'?'Card salvo; confirmando o avanço.':'Lendo e salvando o card antes do avanço.':pendingAdvance?`Card salvo, mas ainda na tela. Pressione ${pendingAdvance.trigger === 'Errei' ? '1' : '2'} novamente.`:active?'Espaço revela · 1 Errei · 2 Difícil. Cada card é gravado diretamente na sessão ativa.':'Nenhuma sessão ativa. Errei/Difícil ficam bloqueados até você iniciar uma sessão.':'Exportação disponível fora da tela de flashcards.');const startButton=panel.querySelector('[data-action="start-session"]');const endButton=panel.querySelector('[data-action="end-session"]');const prepareButton=panel.querySelector('[data-action="prepare"]');const gmSessionButton=panel.querySelector('[data-action="gm-session"]');const copySessionButton=panel.querySelector('[data-action="copy-session"]');const sessionLink=panel.querySelector('[data-role="session-download"]');if(startButton)startButton.disabled=Boolean(active);if(endButton)endButton.disabled=!active;const exportUnavailable=mode==='test'||!latest||latestCards.length===0;if(prepareButton)prepareButton.disabled=exportUnavailable;if(gmSessionButton)gmSessionButton.disabled=exportUnavailable;if(copySessionButton)copySessionButton.disabled=exportUnavailable;const validPrepared=prepared.sessionId===latest?.id&&prepared.sessionTsv&&!exportDirty;if(sessionLink){sessionLink.hidden=!validPrepared;if(validPrepared){sessionLink.href=prepared.sessionUrl;sessionLink.download=prepared.sessionName;sessionLink.textContent=`Baixar TSV da sessão (${prepared.sessionCount})`;}}
set('export-status',mode==='test'?'Para exportar, saia da sessão de flashcards.':validPrepared?`TSV preparado com ${prepared.sessionCount} card(s).`:latestCards.length?`Há ${latestCards.length} card(s) aguardando preparação do TSV.`:'Nenhum card disponível para exportação.');applyPanelState();}
function syncPageMode(){if(pageMode()!=='test'){ratingTransaction=null;pendingAdvance=null;}
renderPanel();}
function installRouteWatcher(){lastKnownPath=String(pageWindow.location?.pathname||'');pageWindow.setInterval?.(()=>{const currentPath=String(pageWindow.location?.pathname||'');if(currentPath===lastKnownPath)return;lastKnownPath=currentPath;syncPageMode();},700);pageWindow.addEventListener?.('popstate',()=>pageWindow.setTimeout?.(syncPageMode,0));pageWindow.addEventListener?.('hashchange',()=>pageWindow.setTimeout?.(syncPageMode,0));}
function installLegacyIsolation(doc=documentRef){const style=doc.createElement('style');style.id='osler-anki-v050-legacy-isolation';style.textContent=`
      #osler-anki-session-controls-v0411,
      #osler-anki-session-controls-v0412 {
        display: none !important;
        pointer-events: none !important;
      }
    `;doc.head?.appendChild(style);OLD_SESSION_IDS.forEach((id)=>{const node=doc.getElementById(id);if(node)node.style.setProperty('display','none','important');});pageWindow.__OSLER_ANKI_UNIFIED_V050__=true;}
async function install(doc=documentRef){if(!doc?.body||doc.getElementById(PANEL_ID))return;['osler-anki-bridge-v042','osler-anki-bridge-v043','osler-anki-bridge-v044','osler-anki-bridge-v045','osler-anki-bridge-v046','osler-anki-bridge-v047','osler-anki-bridge-v048','osler-anki-bridge-v049','osler-anki-bridge-v0410',].forEach((id)=>doc.getElementById(id)?.remove?.());installLegacyIsolation(doc);await loadState();panel=doc.createElement('section');panel.id=PANEL_ID;panel.innerHTML=`
      <div data-role="drag-handle" style="display:flex;align-items:center;gap:8px;cursor:move;touch-action:none;user-select:none;padding:2px 0 6px">
        <strong data-role="panel-title" style="flex:1"></strong>
        <button type="button" data-action="reset-panel" title="Voltar ao canto superior direito" style="min-width:30px">↗</button>
        <button type="button" data-action="toggle-panel" title="Abrir ou minimizar" style="min-width:30px">+</button>
      </div>
      <div data-role="panel-body">
        <div style="border:1px solid #8aa7c7;border-radius:8px;padding:8px;margin-bottom:8px;background:#f5f9ff">
          <strong>Sessão de exportação</strong>
          <div data-role="session-status" style="margin:5px 0"></div>
          <div style="display:flex;gap:4px;flex-wrap:wrap">
            <input data-role="session-name" type="text" placeholder="Ex.: Princípios do SUS" style="flex:1;min-width:180px;padding:5px;box-sizing:border-box">
            <button type="button" data-action="start-session">Nova sessão</button>
            <button type="button" data-action="end-session">Encerrar sessão</button>
          </div>
        </div>

        <div data-role="queue-status"></div>
        <div data-role="run-status" style="margin-top:3px"></div>
        <div data-role="mode-status" style="margin-top:6px"></div>

        <div style="margin-top:7px;display:flex;gap:5px;flex-wrap:wrap">
          <button type="button" data-action="capture">Adicionar card atual</button>
          <button type="button" data-action="prepare">Preparar TSV da sessão</button>
          <a data-role="session-download" href="#" hidden>Baixar TSV da sessão</a>
          <button type="button" data-action="gm-session">Baixar via Violentmonkey</button>
          <button type="button" data-action="copy-session">Copiar TSV</button>
        </div>

        <div data-role="export-status" style="margin-top:6px"></div>
        <div data-role="message" style="margin-top:6px;max-width:450px;overflow-wrap:anywhere"></div>

        <details style="margin-top:8px">
          <summary>Diagnóstico e recuperação</summary>
          <div style="display:flex;gap:5px;flex-wrap:wrap;margin:6px 0">
            <a data-role="log-download" href="#" hidden>Baixar log</a>
            <button type="button" data-action="gm-log">Baixar log via Violentmonkey</button>
            <button type="button" data-action="copy-log">Copiar log</button>
          </div>
          <label>TSV da sessão</label>
          <textarea data-role="session-tsv-text" rows="5" style="width:100%;box-sizing:border-box"></textarea>
          <label>Log</label>
          <textarea data-role="log-text" rows="5" style="width:100%;box-sizing:border-box"></textarea>
          <label>Backup completo</label>
          <textarea data-role="backup-text" rows="6" style="width:100%;box-sizing:border-box"></textarea>
          <button type="button" data-action="import-backup">Importar backup colado</button>
        </details>
      </div>
    `;panel.style.cssText='position:fixed;z-index:2147483647;background:#fff;color:#111;border:1px solid #999;border-radius:10px;padding:8px 10px;font:12px system-ui;width:min(460px,calc(100vw - 16px));box-sizing:border-box;box-shadow:0 4px 18px rgba(0,0,0,.35)';doc.body.appendChild(panel);const run=(operation)=>Promise.resolve().then(operation).catch((error)=>{setMessage(error?.message||String(error),'failed');renderPanel();});panel.querySelector('[data-action="toggle-panel"]').addEventListener('click',()=>{panelState.minimized=!panelState.minimized;applyPanelState();persistPanelState();});panel.querySelector('[data-action="reset-panel"]').addEventListener('click',()=>{panelState.left=null;panelState.top=12;applyPanelState();persistPanelState();});panel.querySelector('[data-action="start-session"]').addEventListener('click',()=>run(async()=>{const input=panel.querySelector('[data-role="session-name"]');await startSession(input?.value||'');if(input)input.value='';}));panel.querySelector('[data-action="end-session"]').addEventListener('click',()=>run(endSession));panel.querySelector('[data-action="capture"]').addEventListener('click',()=>run(()=>capture('captura manual',doc)));panel.querySelector('[data-action="prepare"]').addEventListener('click',()=>run(prepareExports));panel.querySelector('[data-action="gm-session"]').addEventListener('click',()=>run(()=>downloadWithGm('session')));panel.querySelector('[data-action="copy-session"]').addEventListener('click',()=>run(async()=>{if(exportDirty||!prepared.sessionTsv)prepareExports();await copyText(prepared.sessionTsv,'TSV da sessão');}));panel.querySelector('[data-action="gm-log"]').addEventListener('click',()=>run(()=>downloadWithGm('log')));panel.querySelector('[data-action="copy-log"]').addEventListener('click',()=>run(async()=>{if(exportDirty||!prepared.log)prepareExports();await copyText(prepared.log,'Log');}));panel.querySelector('[data-action="import-backup"]').addEventListener('click',()=>run(()=>{const text=panel.querySelector('[data-role="backup-text"]')?.value||'';return importBackup(text);}));installPanelDragging();ensureGlobalListeners(doc);installRouteWatcher();renderPanel();syncPageMode();}
const api={VERSION,activeSession,assignCardToActiveSession,buildSessionTsv,cardsForSession,deriveIdsFromAudit,extractCard,extractResponse,findQuestionElement,isEntirelyItalic,isLikelyReference,mergeCardArrays,mergeSessionStates,normalizeSessionState,questionScore,repairLegacySessions,safeDeckName,slugify,stableHash,topicStartsParagraph,validateCard,};pageWindow.OslerAnkiBridgeV050=api;if(typeof module!=='undefined'&&module.exports){module.exports=api;}else{install().catch((error)=>console.error('[Osler Anki Bridge 0.5.0]',error));}}());
